In [1]:
import numpy as np
from sklearn.decomposition import NMF
from sklearn.preprocessing import normalize

# Create a matrix
matrix = np.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Decompose the matrix into two non-negative matrices
nmf = NMF()
W = nmf.fit_transform(matrix)
H = nmf.components_

# Print the resulting matrices
print(W)
print(H)

# Multiply the matrices together and print the result
result = np.dot(W, H)
print(result)

[[3.44700582e-02 0.00000000e+00 2.58429515e-01]
 [9.04010400e-03 9.38798617e-03 9.82784950e-01]
 [1.26224291e-03 5.30444204e-02 1.57356389e+00]]
[[ 0.         21.55215386 44.45506411]
 [16.04570572  6.44538761  0.        ]
 [ 3.90940827  4.8437584   5.68714662]]
[[1.01030648 1.99467413 3.00209519]
 [3.99274447 5.01571578 5.99112051]
 [7.00283886 7.99105923 9.00520167]]
